# Generated by Django 5.0.1 on 2024-02-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_expirabletoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpirableToken',
        ),
    ]
