# Generated by Django 5.0.1 on 2024-03-06 16:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_expirabletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='AR', unique=True),
        ),
    ]
